### ISSUE TITLE
Missing information on the Dry run report generation configuration in migration guide

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#13924]
**Describe the issue:**
During a Migration testing if you want to generate dry run reports that can be done from the migration-config.yaml. But migration guide doesnt include the correct steps with example on how to do that.

https://is.docs.wso2.com/en/latest/setup/migrating-userstore-managers/#how-to-run Dry Run section

To generate dry run reports we have to pass the reportPath as a string value and this reportPath always needs to be defined under a **parameter** config. If we dont pass it as a string or dont include it under a **parameter** config report generatio will not get success and you will end up in error saying migration process stopped.

So lets include a sample config for the correct way of doing it

<IS_HOME>/migration-resources/migration-config.yaml 

```
name: "GroupsAndRolesMigrator"
    order: 4
    parameters:
       # Absolute path for the dry report. This is required in the dry run mode.
      reportPath: "/home/ubuntu/WSO2/IS600/MigrationTesting/reports"
```

- [x] Mention you need to pass the reportPath as a string value
- [x] Mention you need to define reportPath under a **parameter** config
- [x] Mention that you need to uncomment and include reportPath in the migration-config.yaml uner each migrator that you wants to get the reports generated ( At the moment there are 5 occurences in the migration-config.yaml to uncomment)

Attaching sample config file for reference
[resources.zip](https://github.com/wso2/product-is/files/8888114/resources.zip)
