### ISSUE TITLE
Missing steps on configuring console and myaccount URL Migrator in the migration guide

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#14030]
**Describe the issue:**

When you are migrating from a older IS version for a IS version which supports myaccount and console apps (5.11.0 , IS 6.0.0) if the new IS pack which has the myaccount and console apps are running in a separate port offset value we need to configure the below URLS with the correct port offset values in the migration-config.yaml file before the migration.

If we dont configure the urls with correct portoffset values here after the migration you want be able to access myacoount and console with the default configs. It will give the below error

![Screenshot from 2022-06-16 18-29-37](https://user-images.githubusercontent.com/31848014/175515307-b39bf17f-3de6-40a6-b711-c3264ce65223.png)

Suggesting to get these details added to the migration guide https://is.docs.wso2.com/en/latest/setup/migrating-to-5110/ versions 5.11.0 and 6.0.0

Configuration that is required to do

If IS pack with myaccount and console running on port 9444

```
- name: "SystemAppRedirectURLMigrator"
     order: 15
     parameters:
        consoleRedirectUrl: "regexp=(https://localhost:9444/console|https://localhost:9444/t/(.*)/console)"
        myaccountRedirectUrl: "regexp=(https://localhost:9444/myaccount|https://localhost:9444/t/(.*)/myaccount)"
```
