### ISSUE TITLE
Improve 5.11 migration docs on resolving internal/admin conflict issue.

### ISSUE THREAD

**Issue by Wathsara** [wso2/product-is#14142]
**Describe the issue:**
- There can be a conflict if the internal/admin role is available in the current version. More information refer  https://github.com/wso2/product-is/issues/14085

**Steps**

Need to add the following to the `deployment.toml` of the 5.11

```
[super_admin]
admin_role = "<<New-Admin-Role-Name>>"
create_admin_account = false
```

Then in the Migration client need to add the admin role name of the current version as a parameter under `GroupsAndRolesMigrator`

Example
```
 name: "GroupsAndRolesMigrator"
 order: 4
 parameters:
 currentAdminRoleName: "<<Current-Admin-Role>>"
 ```
 
 Related PRs
 - https://github.com/wso2-extensions/identity-migration-resources/pull/233
