### ISSUE TITLE
Enable JARM by default

### ISSUE THREAD

**Issue by chamathns** [wso2/product-is#16618]
**Describe the issue:**
As of now, JARM feature is disabled by default in IS. There aren't any blockers identified with the feature so it could be enabled by default.

the way to enable it now is, as per: https://is.docs.wso2.com/en/5.10.0/learn/jarm-for-oauth2/

```toml
[oauth.jarm]
jarm_response_jwt_validity = 7200

[[oauth.response_mode]]
name = "jwt"
class = "org.wso2.carbon.identity.oauth2.responsemode.provider.jarm.impl.JwtResponseModeProvider"

[[oauth.response_mode]]
name = "query.jwt"
class = "org.wso2.carbon.identity.oauth2.responsemode.provider.jarm.impl.QueryJwtResponseModeProvider"

[[oauth.response_mode]]
name = "fragment.jwt"
class = "org.wso2.carbon.identity.oauth2.responsemode.provider.jarm.impl.FragmentJwtResponseModeProvider"

[[oauth.response_mode]]
name = "form_post.jwt"
class = "org.wso2.carbon.identity.oauth2.responsemode.provider.jarm.impl.FormPostJwtResponseModeProvider"
```

need to add the above configs to identity.xml.j2 and add a way to disable these on demand as well.
Furthermore, we need to test the flows to make sure /authorize flows do not have any breaking change or migration impact.
