### ISSUE TITLE
[Migration] Support same client Id for applications over different tenants

### ISSUE THREAD

**Issue by ThaminduDilshan** [wso2/product-is#16850]
**Describe the issue:**
Currently in IS client ID is considered to be unique across the server and as a result the same client ID cannot be used in two different tenants. This capability is provided with https://github.com/wso2/product-is/issues/16370 improvement. A migration client should be provided to migrate older users to the new version.

#### Related issue
- https://github.com/wso2/product-is/issues/16370

**Comment by ThaminduDilshan** [comment]
Details and steps should be added to the migration docs.

1. Prerequisites on configs (tenant qualified urls and tenanted sessions)
2. DB constraint update
3. Schema migrator configs
    ```
     -
    version: "7.0.0"
    migratorConfigs:
     -
       name: "ClientIdTenantUnificationMigrator"
       order: 1
       parameters:
         location: "step1"
         schema: "identity"
    ```
