### ISSUE TITLE
Disable the legacy login flow editor (Classic) by default

### ISSUE THREAD

**Issue by brionmario** [wso2/product-is#17219]
**Is your suggestion related to an experience ? Please describe.**

We recently onboarded a brand new Visual Editor for configuring login flows of applications.
And now we can retire the old editor.

**Describe the improvement**

Remove the old editor by default.

<img width="1204" alt="Screenshot 2023-10-26 at 01 20 06" src="https://github.com/wso2/product-is/assets/25959096/3eea18de-3e60-4b96-813d-2c8849d50521">

**Comment by brionmario** [comment]
Disabled with https://github.com/wso2/carbon-identity-framework/pull/5061.

Can be enabled again with the following TOML config.

```toml
[console.applications]
disabled_features=["applications.loginFlow.legacyEditor"]
```
