### ISSUE TITLE
Console & My Account is not registered when `system_applications` array is not empty

### ISSUE THREAD

**Issue by brionmario** [wso2/product-is#17431]
**Describe the issue:**

The following config is needed to make Console & My Account editable. When this config is added, the newly created tenants will not have the Console & My Account.

```toml
[system_applications]
read_only_apps = []
```

<img width="1792" alt="Screenshot 2023-10-31 at 11 29 27" src="https://github.com/wso2/product-is/assets/25959096/f70155cb-3a5f-42b7-908e-cb0390a7d06c">

**How to reproduce:**

1. Add the following TOML config.

```toml
[system_applications]
read_only_apps = []
```

2. Restart the pack.
3. Create a new tenant.
4. Check the service providers section.

**Expected behavior:**

My Account & Console should be created for the tenant.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 7.0 Alpha
 - OS: Mac
 - Database: H2
 - Userstore: LDAP
