### ISSUE TITLE
Remove secret manager related API from IS management API list

### ISSUE THREAD

**Issue by AnuradhaSK** [wso2/product-is#19514]
**Describe the issue:**
Depends on https://github.com/wso2/product-is/issues/19512

When this feature is hidden from IS, the secret manager API is not utilized by default in IS-7.0.0
Hence,

- Remove the API from the default management API of IS (update both xml.j2 and xml file)

https://github.com/wso2/carbon-identity-framework/blob/1ef5f3a7010836d1099f54220eced0864d4679bd/features/api-resource-mgt/org.wso2.carbon.identity.api.resource.mgt.server.feature/resources/system-api-resource.xml.j2#L437-L462

- Remove Access controls of the API (update both xml.j2 and xml file)

https://github.com/wso2/carbon-identity-framework/blob/1ef5f3a7010836d1099f54220eced0864d4679bd/features/identity-core/org.wso2.carbon.identity.core.server.feature/resources/resource-access-control-v2.xml.j2#L150-L176

**Comment by janakamarasena** [comment]
The APIs are not exposed from the sereve by removing them from the resource access control file with [1]. It can be added back to the server through the deployment.toml file.

### Sample configs
identity.xml and resource-access-control-v2.xml
```toml
[[resource.access_control]]
context="(.*)/api/server/v1/secret-type(.*)"
permissions = ["/permission/admin/manage/identity/secretmgt/add"]
scopes= ["internal_secret_mgt_add"]
secure=true
http_method="all"
```

api-resource-collection.xml
```toml
[[api_resource_collections]]
name = "secretsManagement"
displayName = "Secrets Management"
type = "tenant"
enabled = true
[[api_resource_collections.scopes.create]]
name = "internal_secret_mgt_add"
[[api_resource_collections.scopes.update]]
name = "internal_secret_mgt_update"
[[api_resource_collections.scopes.read]]
name = "internal_secret_mgt_view"
[[api_resource_collections.scopes.delete]]
name = "internal_secret_mgt_delete"
```

system-api-resource.xml
```toml
[[api_resources]]
name = "Secret Type Management API"
identifier = "/api/server/v1/secret-type"
requiresAuthorization = true
description = "API representation of the Secret Type Management API"
type = "TENANT"
[[api_resources.scopes]]
displayName = "Add Secret Type"
name = "internal_secret_type_mgt_add"
[[api_resources.scopes]]
displayName = "Update Secret Type"
name = "internal_secret_type_mgt_update"
```




[1] - https://github.com/wso2/carbon-identity-framework/pull/5511
