### ISSUE TITLE
[Migration Client] Error when dropping the index UM_ROLE_NAME from UM_HYBRID_ROLE table.

### ISSUE THREAD

**Issue by pandukakarunasena** [wso2/product-is#20814]
**Describe the issue:**
When running the migration client in SchemaMigrator of version 7.0.0 order 3,

```
   version: "7.0.0"
   migratorConfigs:
  -------------------------------------------------------------
     - name: "SchemaMigrator"
       order: 3
       parameters:
         location: "step1"
         schema: "um"
```

Below SQL ERROR can be seen.

`Caused by: java.sql.SQLSyntaxErrorException: Can't DROP 'UM_ROLE_NAME'; check that column/key exists
`
This occurs because of the below SQL query:

```
ALTER TABLE UM_HYBRID_ROLE
	ADD COLUMN UM_AUDIENCE_REF_ID INTEGER DEFAULT -1 NOT NULL,
        ADD COLUMN UM_UUID VARCHAR(36),
	**DROP INDEX UM_ROLE_NAME,**
	ADD CONSTRAINT UM_AUDIENCE_REF_ID UNIQUE (UM_ROLE_NAME, UM_TENANT_ID, UM_AUDIENCE_REF_ID);
```

There is no index created for UM_HYBRID_ROLE with the name UM_ROLE_NAME. Upon further inspection of the migration resources, there is no indication of an index being created named UM_ROLE_NAME. However, in the file _migration-resources/5.9.0/dbscripts/step2/carbon/mysql-cluster-5.7.sql_, an index is created for the same column but with a different name, `UM_ROLE_NAME_IND`

**How to reproduce:**
Run the migration client to version 7.0.0 with any version.

**Expected behavior:**
The index should be created by the migration client in an earlier step if it does not already exist, under the name UM_ROLE_NAME_IND.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
migration client

---
