### ISSUE TITLE
[Migration Client] ALTER_SP_SHARED_APP stored procedure is not executed properly for Mysql

### ISSUE THREAD

**Issue by ShehanDinuka** [wso2/product-is#20854]
**Describe the issue:**
When running the migration client in SchemaMigrator of version 7.0.0 order 2,
```
   version: "7.0.0"
   migratorConfigs:
-----------------------------------------
     - name: "SchemaMigrator"
       order: 2
       parameters:
         location: "step1"
         schema: "identity"
     - name: "SchemaMigrator"
```
ALTER_SP_SHARED_APP stored procedure for mysql is not executing properly when there are other schemas with `TABLE_NAME='SP_SHARED_APP' AND COLUMN_NAME='SHARE_WITH_ALL_CHILDREN'`

**How to reproduce:**

- Create a Database with IS 7.0 identity schema, which has `SP_SHARED_APP` table with `SHARE_WITH_ALL_CHILDREN ` column.
- Run the migration to IS 7.0 on database which needed to be migrated.
- At the end of the migration, it can be observed that `SHARE_WITH_ALL_CHILDREN` column is not added to `SP_SHARED_APP` table.

**Expected behavior:**

`SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='SP_SHARED_APP' AND COLUMN_NAME='SHARE_WITH_ALL_CHILDREN'` 

Above query will be run to check `SP_SHARED_APP` table has the `SHARE_WITH_ALL_CHILDREN` column. The query is currently checking all the databases. If any schema has the SP_SHARED_APP table with SHARE_WITH_ALL_CHILDREN column, it will not run the alteration on migrating SP_SHARED_APP table.  It should only check the database that is being migrated.

This can be corrected by setting the current database in the select query as below.

`SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='SP_SHARED_APP' AND COLUMN_NAME='SHARE_WITH_ALL_CHILDREN' and TABLE_SCHEMA = (SELECT DATABASE())`

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [Migrating to IS 7.0]
 - OS: [Mac]
 - Database: [ MySQL]
 - Userstore: [ JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**
