### ISSUE TITLE
[Migration Doc] Clarifications on the migrationOption of the LegacyToNewRuntimeMigrator

### ISSUE THREAD

**Issue by ShehanDinuka** [wso2/product-is#21030]
**Is your suggestion related to a missing or misleading document? Please describe.**

The migration documentation currently lacks specific details on the options that need to be configured under `migrationOption` in the `LegacyToNewRuntimeMigrator` section of the `migration-config.yaml` file. However, a comment mentioned that these options are related to the management application.

Please provide instructions on the required configurations and their use cases. Additionally, consider incorporating this information into the relevant migration documentation.
```
name: "LegacyToNewRuntimeMigrator"
       order: 5
       parameters:
         # Absolute path for the dry report. This is required in the dry run mode.
         reportPath: <absolute-path>
         # Management app migration option. Ex:- 2 or 3
         migrationOption: <option>
```
**Describe the improvement**

- Incorporate above mentioned information into the relevant migration documentation.
