### ISSUE TITLE
Newly Added Internal Org Scopes for an Existing API are Not Allowed for Child Organization Admin

### ISSUE THREAD

**Issue by dhaura** [wso2/product-is#21306]
**Describe the issue:**
When a new internal organization (prefixed with `internal_org`) scope is added to an existing registered system API, that scope is not allowed for the child organiaztion admin.

**How to reproduce:**
1. If the IS pack is fresh, start it at least once.
2. Add a new internal organization (prefixed with `internal_org`) scope to an existing API path through `deployment.toml`.
EX: 
```toml
[[api_resources]]
name = "Email Template Management API v1/v2"
identifier = "/o/api/server/v(.*)/email/template-types"
requiresAuthorization = true
description = "API representation of the Email Template Management API"
type = "ORGANIZATION"

[[api_resources.scopes]]
displayName = "Create Email Template"
name = "internal_org_email_mgt_create"
description = "Create new email template and types in the organization"
```
3. Restart the IS server.
4. Log into Console with admin credentials with the inspect tab open.
5. Copy the token issued for the Console.
6. Use introspection endpoint to explore the scopes related the copied token in step 5.
7. Verify that the new scope is included.
8. Switch into a child organization with inspect tab open.
9. Copy the token issued when switching to the organization.
10. Use introspection endpoint to explore the scopes related the copied token in step 9.
11. Verify that the new scope is NOT included.

**Expected behavior:**
Newly added internal organization scope should be available for child organizations as well.

**Environment information**:**
 - Product Version: `IS 7.1.0-m2-SNAPSHOT`
 - OS: `macos`
 - Database: `h2`
 - Userstore: `default`
