### ISSUE TITLE
Invalid Field Type in OpenAPI Spec for Pre-Issue-Access-Token

### ISSUE THREAD

**Issue by malithie** [wso2/product-is#21312]
**Describe the issue:**
Describe the Issue:
The given OpenAPI spec for the pre-issue-access-token mentions the AccessTokenClaims as follows.

```
AccessTokenClaims:
      type: object
      properties:
        name:
          type: string
        value:
          type: string
However, the actual request from the asgardeo includes int and string[] values as AccessTokenClaims values. The type of the value field should be changed accordingly.
```

**How to reproduce:**
Check the API contract in the documentation

**Expected behavior:**
Since we allow String, Integer, Boolean and String[] types for the value attribute of the claims object, the OpenAPI contract in the documentation need to properly be updated.
