### ISSUE TITLE
Add New System Scopes for Notification/ Email Template Management APIs

### ISSUE THREAD

**Issue by dhaura** [wso2/product-is#21980]
### Document issue type

Type/Task (Operational or administrative tasks related to the documentation)

### Description
- The following scopes a introduced in Notification and Email template management APIs in order to enable child org overriding capabilities in notification templates.
    - Email v1/ v2 API
        - `POST` /o/api/server/v(.*)/email/template-types - `internal_org_email_mgt_create`
        - `PUT` /o/api/server/v(.*)/email/template-types - `internal_org_email_mgt_update`
        - `DELETE` /o/api/server/v(.*)/email/template-types - `internal_org_email_mgt_delete`
    - Notification API
        -  `POST` /o/api/server/v(.*)/notification/(?:email|sms)/template-type - `internal_org_template_mgt_create`
        -  `PUT`  /o/api/server/v(.*)/notification/(?:email|sms)/template-type - `internal_org_template_mgt_update`
        - `DELETE`  /o/api/server/v(.*)/notification/(?:email|sms)/template-type - `internal_org_template_mgt_delete`
- Due to the current limitations when reading and persisting new scopes to the DB, the users who are migrating to IS 7.1 should add the below configuration to the `deployment.toml` file.
```toml
[[api_resources]]
name = "Email Template Management API v1/v2"
identifier = "/o/api/server/v(.*)/email/template-types"
requiresAuthorization = true
description = "API representation of the Email Template Management API"
type = "ORGANIZATION"

[[api_resources.scopes]]
displayName = "View Email Template"
name = "internal_org_email_mgt_view"
description = "View email templates and types in the organization"

[[api_resources.scopes]]
displayName = "Create Email Template"
name = "internal_org_email_mgt_create"
description = "Create email templates and types in the organization"

[[api_resources.scopes]]
displayName = "Update Email Template"
name = "internal_org_email_mgt_update"
description = "Update email templates and types in the organization"

[[api_resources.scopes]]
displayName = "Delete Email Template"
name = "internal_org_email_mgt_delete"
description = "Delete email templates and types in the organization"
```
```toml
[[api_resources]]
name = "Notification Template Management API"
identifier = "/o/api/server/v(.*)/notification/(?:email|sms)/template-types"
requiresAuthorization = true
description = "API representation of the Notification Template Management API"
type = "ORGANIZATION"

[[api_resources.scopes]]
displayName = "View Notification Template"
name = "internal_org_template_mgt_view"
description = "View notification templates and types in the organization"

[[api_resources.scopes]]
displayName = "Create Notification Template"
name = "internal_org_template_mgt_create"
description = "Create notification templates and types in the organization"

[[api_resources.scopes]]
displayName = "Update Notification Template"
name = "internal_org_template_mgt_update"
description = "Update notification templates and types in the organization"

[[api_resources.scopes]]
displayName = "Delete Notification Template"
name = "internal_org_template_mgt_delete"
description = "Delete notification templates and types in the organization"
```

### Related Issues
- https://github.com/wso2/product-is/issues/21214

### Related PRs
- 

### Version

7.1.0-m6-SNAPSHOT
