### ISSUE TITLE
Improve deployment documentation

### ISSUE THREAD

**Issue by madurangasiriwardena** [wso2/product-is#22183]
### Document issue type

Type/Improvement (Suggest changes to enhance the clarity, usability, or accuracy of existing content)

### Description

Pages in the deploy section is not clear and intuitive. We should organize the pages and content within them in a more clear way.

https://is.docs.wso2.com/en/latest/deploy/deployment-guide/

### Version

IS 7.0.0

**Comment by hwupathum** [comment]
Suggestion
```yaml
- Deploy:
  - Deployment Overview & Fundamentals:
    - Deployment Patterns: deploy/deployment-guide.md
    - Deployment Checklist: deploy/deployment-checklist.md
    - Product Compatibility: deploy/product-compatibility.md
    - Change the Hostname: deploy/change-the-hostname.md
    - Promote Configurations Across Environments: deploy/promote-configurations.md
  - High Availability (HA) & Clustering:
    - WSO2 Clusters with Nginx: deploy/front-with-the-nginx-load-balancer.md
    - Databases for Clustering: deploy/set-up-separate-databases-for-clustering.md
    - Configure Hazelcast: deploy/configure-hazelcast.md
  - Scaling WSO2 Identity Server:
    - Performance Tuning Recommendations: deploy/performance/performance-tuning-recommendations.md
    - Configure Cache Layers: deploy/performance/configure-cache-layers.md
  - Containerized Deployments:
    - Kubernetes: deploy/deploy-is-on-kubernetes.md
    - OpenShift: deploy/deploy-is-on-openshift.md
  - Multi-Data Center Deployments (Disaster Recovery):
    - Understanding Disaster Recovery: deploy/disaster-recovery/understanding-disaster-recovery.md
    - Deployment Patterns: deploy/disaster-recovery/disaster-recovery-deployment-patterns.md
    - Additional Reading: deploy/disaster-recovery/additional-reading-on-disaster-recovery.md
  - Maintenance & Troubleshooting in Production:
    - Backup and Recovery Recommendations: deploy/backup-and-recovery-recommendations.md
    - Troubleshoot in Production Environments: deploy/monitor/troubleshoot-in-production-environments.md
```
