### ISSUE TITLE
[IS - 7.2 Migration] Changing the default value of the send_only_otp_as_confirmation_code

### ISSUE THREAD

**Issue by Malith-19** [wso2/product-is#23480]
### Description

The default value of the `identity_mgt.password_reset_email.otp.send_only_otp_as_confirmation_code` has been set to true as default now as in email OTP scenario confirmation code should be the OTP value.

If any users using the default "false" value previously, they need to add the following configuration to the deployment.toml to ensure the backward compatibility.

```toml
[identity_mgt.password_reset_email.otp]
send_only_otp_as_confirmation_code = false
```

### Related issues
- https://github.com/wso2/product-is/issues/23444
