### ISSUE TITLE
Wrong regex used for validation of the email address field during user creation on the Console application

### ISSUE THREAD

**Issue by vfraga** [wso2/product-is#23753]
### Description

The email address field in the user creation screen [1] incorrectly uses the value of the `UsernameJavaScriptRegEx` user store property for validation of the field.

This was most likely done due to the email as username feature [2], but a validation error shows up even with the feature off.

### Steps to Reproduce

1. Create a WSO2 IS 7.1.0 instance.
2. Add the configuration below to the `<IS_HOME>/repository/conf/deployment.toml` file:
	```toml
	[user_store]
	// . . . [omitted existing configurations] . . .
	username_java_regex = "^((?=.*\\d)(?=.*[a-z])).{8,20}$"
	username_java_script_regex = "^((?=.*\\d)(?=.*[a-z])).{8,20}$"
	```
3. In the Console application, try creating a user with username `testuser01` and email address `first.name@mailprovider.mail.org`.

### Version

7.1.0.1

### Environment Details (with versions)

N/A

---

[1] https://is.docs.wso2.com/en/7.1.0/guides/users/manage-users/#onboard-single-user
[2] https://is.docs.wso2.com/en/latest/guides/users/attributes/enable-email-as-username/
