### ISSUE TITLE
[Docs] Need a way to define feature status on the docs side panel via `nav_chip`

### ISSUE THREAD

**Issue by brionmario** [wso2/product-is#23945]
### Current Limitation

Currently `nav_chip` has the support to show an `ai` chip but it needs to be a bit improved to handle other feature statuses like:
- `New`
- `Beta`
- `Preview`
- `Premium`

### Suggested Improvement

Give the support to display feature statuses.

**Comment by brionmario** [comment]
In the `mkdocs.yml` pass the feature statuses like the following.

1. Preview Feature

    <img width="217" alt="Image" src="https://github.com/user-attachments/assets/e152f572-18e2-4397-a2ed-8498f4cf6370" />

    ```yml
      nav_chip:
        Self-register flow:
          type: Preview
          level: 4
    ```

2. Premium Feature

    <img width="206" alt="Image" src="https://github.com/user-attachments/assets/10ea9bf1-fcf4-408e-b0df-7e3dfbad53fe" />

    ```yml
      nav_chip:
        Self-register flow:
          type: Premium
          level: 4
    ```

3. Beta Feature

    <img width="210" alt="Image" src="https://github.com/user-attachments/assets/f994e6c3-517c-44a6-a21b-7a60ccc46586" />

    ```yml
      nav_chip:
        Self-register flow:
          type: Premium
          level: 4
    ```

4. New Feature

    <img width="203" alt="Image" src="https://github.com/user-attachments/assets/b3cbf170-44fa-43e7-a49a-db5bfb99af03" />

    ```yml
      nav_chip:
        Self-register flow:
          type: New
          level: 4
    ```
