### ISSUE TITLE
[Migration Docs] Add Challenge Question Connector Migration Documentation

### ISSUE THREAD

**Issue by Osara-B** [wso2/product-is#24090]
### Document issue type

Type/NewFeature (Propose new topics or content to improve usability or provide additional value)

### Description

Starting from WSO2 Identity Server (IS) 7.1.0, the Challenge Questions feature has been refactored into a connector. From IS 7.2.0 onwards, support for storing challenge questions in the database has been introduced with https://github.com/wso2-extensions/identity-challenge-questions/pull/21 .

These changes need to be added to the IS 7.2.0 migration documentation.

Migration Steps:
Enable the updated Challenge Questions Connector in the new IS 7.2.0 pack.

Create the IDN_CHALLENGE_QUESTION table in the identity database using the SQL scripts provided in <CONNECTOR_HOME>/dbscripts.

To migrate challenge questions from the registry to the database, add the following configuration to the migration-config.yaml:

```
    - name: "ChallengeQuestionMigrator"
      order: 1
      parameters:
        waitTime: 100
        rollbackAllowed: "true"
```

This configuration should only be included when the Challenge Questions connector is enabled and a migration is intended.

### Version

IS 7.2.0
