### ISSUE TITLE
Demo authenticators doesn't work

### ISSUE THREAD

**Issue by pulasthi7** [wso2/product-is#6328]
The demo fingerprint/HW key authenticators gives a 401 when deployed.

Added the following to TOML file to get that fixed.

```toml
[[resource.access_control]]
context = "/sample-auth/(.*)"
secure = false
http_method = "all"
```

Now, it's giving a 500 error. No logs at the backend.
![image](https://user-images.githubusercontent.com/1415573/64075349-d29abc80-ccd4-11e9-9ba6-7cc944d754ce.png)
