### ISSUE TITLE
Update product observability doc Single header and Multi header configs

### ISSUE THREAD

**Issue by Buddhimah** [wso2/product-is#6695]
With the PR https://github.com/wso2/docs-is/pull/591
Single header and multi header configs are removed. due to the issue https://github.com/wso2/product-is/issues/6690

After the issue is fixed need to update it as follows. 

  Change the `           RequestCorrelationIdValve          ` in the
   `           <IS_HOME>/repository/conf/deployment.toml          ` file to the value given
   below.

   ``` toml
   [log_correlation]
   header_config = "{'customHeader1':'Correlation-ID', 'customHeader2':'Second-Correlation-ID'}"
   ```

https://is.docs.wso2.com/en/5.9.0/administer/working-with-product-observability/#
