### ISSUE TITLE
Improve error message for input validations in identity-rest-dispatcher

### ISSUE THREAD

**Issue by mefarazath** [wso2/product-is#6888]
With our current implementation, we can defined input validations at the swagger level and when validations fail the [input validation exception mapper](https://github.com/wso2/identity-rest-dispatcher/blob/83b7f220f4fe030c8f6de91eb309a227e898f2eb/components/org.wso2.carbon.identity.api.dispatcher/src/main/java/org/wso2/carbon/identity/api/dispatcher/InputValidationExceptionMapper.java#L36) class handles building the necessary API level errors.

This works well for all the common scenarios. There is one scenario where we can improve the error message.

We can define a minimum or maximum for array types in swagger. 
Example:

```
    OpenIDConnectConfiguration:
      type: object
      required:
        - grantTypes
      properties:
        clientId:
          type: string
        clientSecret:
          type: string
        state:
          type: string
          enum:
            - ACTIVE
            - REVOKED
          readOnly: true
          default: ACTIVE
        grantTypes:
          type: array
          example:
            - authorization_code
            - password
          items:
            type: string
          minItems: 1
```

When such a constraint is defined and the request fails the input validation, the current error message thrown is,

```
{
    "code": "UE-10000",
    "message": "Invalid Request",
    "description": "size must be between 1 and 2147483647",
    "traceId": "5d96d5c2-ae80-467c-8aa0-15d1694d89e4"
}
```

It would be better to include which field violates the constraint.
