### ISSUE TITLE
Unable to change OIDC session management configs in portal deployment config from TOML

### ISSUE THREAD

**Issue by brionmario** [wso2/product-is#9255]
**Describe the issue:**
When trying to override the default OIDC session management configs (userIdleTimeOut, checkSessionInterval etc) in portal `deployment.config.json`, the TOML configurations do not replace the values as expected.

**How to reproduce:**
1. Go to `deployment.toml` in an IS pack.
2. Add the following configs in the file.

```toml
[console]
session.params.userIdleTimeOut = 90000
session.params.userIdleWarningTimeOut = 89980
session.params.sessionRefreshTimeOut = 1800
session.params.checkSessionInterval = 5

[user_portal]
session.params.userIdleTimeOut = 89980
session.params.userIdleWarningTimeOut = 89980
session.params.sessionRefreshTimeOut = 1800
session.params.checkSessionInterval = 5
```
3. Restart the server.
4. Check the `deploymenyt.config.json` in `console` and `user_portal` webapps.

console/deployment.json
```json
"session": {
            "userIdleTimeOut": 90000,
            "userIdleWarningTimeOut": 580.0,
            "sessionRefreshTimeOut": 300.0,
            "checkSessionInterval": 3.0
    },
```

user-portal/deployment.json
```json
"session": {
                "userIdleTimeOut": 600.0,
                "userIdleWarningTimeOut": 89980,
                "sessionRefreshTimeOut": 1800,
                "checkSessionInterval": 5
    },
```
5. Only `userIdleTimeOut` is changed in console/deployment.json & `userIdleTimeOut`  is not changing.

**Expected behavior:**
The configs should be successfully overriden.

**Possible reasons:**
Having the configs in a nested object might be causing the issue.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version:  IS 5.11.0 M32
 - OS: Mac
 - Database: H2
 - Userstore: LDAP, JDBC
